[package]
name = "alfred_bridge"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.133"
serde_with = "3.11.0"
typed-builder = "0.20.0"

[dev-dependencies]
insta = { version = "1.41.1", features = ["json"] }
